sudo: required

language: ruby
rvm:
  - 2.1
  - 2.2
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mono-devel
  - chmod +x bin/TestServer/TestServer.exe

script:
  - bundle exec rspec --color --format documentation spec

cache:
  - apt

branches:
  only:
    - master
