sudo: required
dist: trusty

addons:
  apt:
    packages:
      - mono-devel

language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - gem install bundler
  - chmod +x bin/TestServer/TestServer.exe

script:
  - bundle exec rspec --color --format documentation spec

cache:
  - apt
