sudo: required
dist: trusty

addons:
  apt:
    sources:
      - mono
    packages:
      - mono-devel
      - p7zip-full

language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rbx-2

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2

before_install:
  - gem install bundler

script:
  - bundle exec rspec

cache:
  - apt
