
### Generated by rprotoc. DO NOT EDIT!

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module KRPC
  module PB
    class Request < ::Protobuf::Message
      defined_in __FILE__
      required :string, :service, 1
      required :string, :procedure, 2
      repeated :Argument, :arguments, 3
    end
    class Argument < ::Protobuf::Message
      defined_in __FILE__
      required :uint32, :position, 1
      required :bytes, :value, 2
    end
    class Response < ::Protobuf::Message
      defined_in __FILE__
      required :double, :time, 1
      optional :string, :error, 2
      optional :bytes, :return_value, 3
    end
    class StreamMessage < ::Protobuf::Message
      defined_in __FILE__
      repeated :StreamResponse, :responses, 1
    end
    class StreamResponse < ::Protobuf::Message
      defined_in __FILE__
      required :uint32, :id, 1
      required :Response, :response, 2
    end
    class Services < ::Protobuf::Message
      defined_in __FILE__
      repeated :Service, :services, 1
    end
    class Service < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      repeated :Procedure, :procedures, 2
      repeated :Class, :classes, 3
      repeated :Enumeration, :enumerations, 4
      optional :string, :documentation, 5
    end
    class Procedure < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      repeated :Parameter, :parameters, 2
      optional :string, :return_type, 3
      repeated :string, :attributes, 4
      optional :string, :documentation, 5
    end
    class Parameter < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      required :string, :type, 2
      optional :bytes, :default_argument, 3
    end
    class Class < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      optional :string, :documentation, 2
    end
    class Enumeration < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      repeated :EnumerationValue, :values, 2
      optional :string, :documentation, 3
    end
    class EnumerationValue < ::Protobuf::Message
      defined_in __FILE__
      required :string, :name, 1
      required :int32, :value, 2
      optional :string, :documentation, 3
    end
    class List < ::Protobuf::Message
      defined_in __FILE__
      repeated :bytes, :items, 1
    end
    class Dictionary < ::Protobuf::Message
      defined_in __FILE__
      repeated :DictionaryEntry, :entries, 1
    end
    class DictionaryEntry < ::Protobuf::Message
      defined_in __FILE__
      required :bytes, :key, 1
      required :bytes, :value, 2
    end
    class Set < ::Protobuf::Message
      defined_in __FILE__
      repeated :bytes, :items, 1
    end
    class Tuple < ::Protobuf::Message
      defined_in __FILE__
      repeated :bytes, :items, 1
    end
    class Status < ::Protobuf::Message
      defined_in __FILE__
      required :string, :version, 1
      required :uint64, :bytes_read, 2
      required :uint64, :bytes_written, 3
      required :float, :bytes_read_rate, 4
      required :float, :bytes_written_rate, 5
      required :uint64, :rpcs_executed, 6
      required :float, :rpc_rate, 7
      required :bool, :one_rpc_per_update, 8
      required :uint32, :max_time_per_update, 9
      required :bool, :adaptive_rate_control, 10
      required :bool, :blocking_recv, 11
      required :uint32, :recv_timeout, 12
      required :float, :time_per_rpc_update, 13
      required :float, :poll_time_per_rpc_update, 14
      required :float, :exec_time_per_rpc_update, 15
      required :uint32, :stream_rpcs, 16
      required :uint64, :stream_rpcs_executed, 17
      required :float, :stream_rpc_rate, 18
      required :float, :time_per_stream_update, 19
    end
  end  
end

