# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: krpc.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "krpc.schema.Request" do
    optional :service, :string, 1
    optional :procedure, :string, 2
    repeated :arguments, :message, 3, "krpc.schema.Argument"
  end
  add_message "krpc.schema.Argument" do
    optional :position, :uint32, 1
    optional :value, :bytes, 2
  end
  add_message "krpc.schema.Response" do
    optional :time, :double, 1
    optional :has_error, :bool, 2
    optional :error, :string, 3
    optional :has_return_value, :bool, 4
    optional :return_value, :bytes, 5
  end
  add_message "krpc.schema.StreamMessage" do
    repeated :responses, :message, 1, "krpc.schema.StreamResponse"
  end
  add_message "krpc.schema.StreamResponse" do
    optional :id, :uint32, 1
    optional :response, :message, 2, "krpc.schema.Response"
  end
  add_message "krpc.schema.Services" do
    repeated :services, :message, 1, "krpc.schema.Service"
  end
  add_message "krpc.schema.Service" do
    optional :name, :string, 1
    repeated :procedures, :message, 2, "krpc.schema.Procedure"
    repeated :classes, :message, 3, "krpc.schema.Class"
    repeated :enumerations, :message, 4, "krpc.schema.Enumeration"
    optional :documentation, :string, 5
  end
  add_message "krpc.schema.Procedure" do
    optional :name, :string, 1
    repeated :parameters, :message, 2, "krpc.schema.Parameter"
    optional :has_return_type, :bool, 3
    optional :return_type, :string, 4
    repeated :attributes, :string, 5
    optional :documentation, :string, 6
  end
  add_message "krpc.schema.Parameter" do
    optional :name, :string, 1
    optional :type, :string, 2
    optional :has_default_value, :bool, 3
    optional :default_value, :bytes, 4
  end
  add_message "krpc.schema.Class" do
    optional :name, :string, 1
    optional :documentation, :string, 2
  end
  add_message "krpc.schema.Enumeration" do
    optional :name, :string, 1
    repeated :values, :message, 2, "krpc.schema.EnumerationValue"
    optional :documentation, :string, 3
  end
  add_message "krpc.schema.EnumerationValue" do
    optional :name, :string, 1
    optional :value, :int32, 2
    optional :documentation, :string, 3
  end
  add_message "krpc.schema.List" do
    repeated :items, :bytes, 1
  end
  add_message "krpc.schema.Dictionary" do
    repeated :entries, :message, 1, "krpc.schema.DictionaryEntry"
  end
  add_message "krpc.schema.DictionaryEntry" do
    optional :key, :bytes, 1
    optional :value, :bytes, 2
  end
  add_message "krpc.schema.Set" do
    repeated :items, :bytes, 1
  end
  add_message "krpc.schema.Tuple" do
    repeated :items, :bytes, 1
  end
  add_message "krpc.schema.Status" do
    optional :version, :string, 1
    optional :bytes_read, :uint64, 2
    optional :bytes_written, :uint64, 3
    optional :bytes_read_rate, :float, 4
    optional :bytes_written_rate, :float, 5
    optional :rpcs_executed, :uint64, 6
    optional :rpc_rate, :float, 7
    optional :one_rpc_per_update, :bool, 8
    optional :max_time_per_update, :uint32, 9
    optional :adaptive_rate_control, :bool, 10
    optional :blocking_recv, :bool, 11
    optional :recv_timeout, :uint32, 12
    optional :time_per_rpc_update, :float, 13
    optional :poll_time_per_rpc_update, :float, 14
    optional :exec_time_per_rpc_update, :float, 15
    optional :stream_rpcs, :uint32, 16
    optional :stream_rpcs_executed, :uint64, 17
    optional :stream_rpc_rate, :float, 18
    optional :time_per_stream_update, :float, 19
  end
end

module KRPC
  module PB
    Request = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Request").msgclass
    Argument = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Argument").msgclass
    Response = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Response").msgclass
    StreamMessage = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.StreamMessage").msgclass
    StreamResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.StreamResponse").msgclass
    Services = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Services").msgclass
    Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Service").msgclass
    Procedure = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Procedure").msgclass
    Parameter = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Parameter").msgclass
    Class = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Class").msgclass
    Enumeration = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Enumeration").msgclass
    EnumerationValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.EnumerationValue").msgclass
    List = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.List").msgclass
    Dictionary = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Dictionary").msgclass
    DictionaryEntry = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.DictionaryEntry").msgclass
    Set = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Set").msgclass
    Tuple = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Tuple").msgclass
    Status = Google::Protobuf::DescriptorPool.generated_pool.lookup("krpc.schema.Status").msgclass
  end
end
